export enum ROLES {
  USER,
  ADMIN,
}

export enum INDEXES {
  NORMALIZED_DIFFERENCE_VEGETATION_INDEX = 'NDVI',
  NORMALIZED_DIFFERENCE_WATER_INDEX = 'NDWI',
  ENHANCE_VEGETATION_INDEX = 'EVI',
  RATIO_VEGETATION_INDEX = 'RVI',
  VISIBLE_ATMOSPHERICALLY_RESISTANT_INDEX = 'VARI',
  VISIBLE_BAND_DIFFERENCE_VEGETATION_INDEX = 'VDVI',
  TRANSFORMED_DIFFERENCE_VEGETATION_INDEX = 'TDVI',
  PERPENDICULAR_VEGETATION_INDEX = 'PVI',
  SOIL_ADJUSTED_VEGETATION_INDEX = 'SAVI',
  MODIFIED_SOIL_ADJUSTED_VEGETATION_INDEX = 'MSAVI',
  OPTIMIZED_SOIL_ADJUSTED_VEGETATION_INDEX = 'OSAVI',
  LEAF_AREA_INDEX = 'LAI',
  CHLOROPHYLL_VEGETATION_INDEX = 'CVI',
  CHLOROPHYLL_INDEX_WITH_RED_EDGE = 'Clre',
  VEGETATION_CONDITION_INDEX = 'VCI',
}
